// src/setupHook.js
// ESM: install a per-repo .git/hooks/post-commit that calls the installed package runtime.
//
// Behavior:
// - When run inside a consumer repo (postinstall), it writes a hook that calls
//   node "<projectRoot>/node_modules/auto-changelog-ai/src/run.js" || true
// - When run inside the package repo itself (dev), it writes a hook that calls
//   node "./src/run.js" || true
//
// The script is safe: if .git/hooks doesn't exist we log and skip.

import { promises as fs } from 'fs';
import path from 'path';
import { chmod } from 'fs/promises';
import { createRequire } from 'module';

async function setupHook() {
  try {
    const projectRoot = process.cwd(); // in postinstall this is the consuming project's root
    const hooksDir = path.join(projectRoot, '.git', 'hooks');
    const hookPath = path.join(hooksDir, 'post-commit');

    // Determine target runner path:
    // 1) If consumer installed package, prefer: <projectRoot>/node_modules/auto-changelog-ai/src/run.js
    // 2) Else (dev inside package repo), fallback to: <projectRoot>/src/run.js
    let runnerPath;

    // Try to resolve package installation using node resolution from projectRoot
    try {
      const requireFromProject = createRequire(path.join(projectRoot, 'noop.js')); // dummy
      // Try to resolve the package.json of the installed package
      const pkgJsonPath = requireFromProject.resolve('auto-changelog-ai/package.json');
      const pkgRoot = path.dirname(pkgJsonPath);
      // Prefer the run entry in the installed package
      const candidate = path.join(pkgRoot, 'src', 'run.js');
      runnerPath = candidate;
    } catch (err) {
      // Could not resolve via node resolution - likely running inside the package repo itself
      runnerPath = path.join(projectRoot, 'src', 'run.js');
    }

    // If runner path doesn't exist, still write hook using node_modules path (best-effort)
    // (This helps for newly-created consumer repos where run.js will appear after installation).
    const exists = await fileExists(runnerPath);

    // Build hook content.
    // Use an absolute path to node script to avoid relative path issues from hooks.
    // We will use the projectRoot variable to create an absolute path to the runner.
    // Note: prefer quoting the path to handle spaces.
    const absoluteRunner = path.resolve(runnerPath);
    const hookContent = `#!/bin/sh
# Auto-generated by auto-changelog-ai
# This hook attempts to run the package's changelog generator.
node "${absoluteRunner}" || true
`;

    // Ensure .git/hooks exists
    try {
      await fs.access(hooksDir);
    } catch (err) {
      console.warn('[auto-changelog-ai] .git/hooks not found at', hooksDir, '- skipping hook installation (not a git repo?)');
      return;
    }

    // Write hook
    await fs.writeFile(hookPath, hookContent, { mode: 0o755 });
    // Ensure executable
    await chmod(hookPath, 0o755);

    console.log('[auto-changelog-ai] Installed post-commit hook ->', hookPath);
    if (!exists) {
      console.log('[auto-changelog-ai] Note: runner script not found at', absoluteRunner, '(it may appear after npm finishes installing dependencies).');
    }
  } catch (err) {
    console.warn('[auto-changelog-ai] Failed to install git hook:', err && err.message ? err.message : String(err));
  }
}

async function fileExists(p) {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

// Run if executed directly (npm postinstall runs node ./src/setupHook.js)
if (import.meta.url === `file://${process.cwd()}/src/setupHook.js`) {
  setupHook();
}

export default setupHook;
