// src/setupHook.js
// Creates or updates the .git/hooks/post-commit hook so that the changelog
// generator runs automatically after each commit.

import { promises as fs } from 'fs';
import path from 'path';
import { chmod } from 'fs/promises';

async function setupHook() {
  try {
    const repoRoot = process.cwd();
    const hooksDir = path.join(repoRoot, '.git', 'hooks');
    const hookPath = path.join(hooksDir, 'post-commit');

    // Git hook content
    const hookContent =
`#!/bin/sh
# Auto-generated by auto-changelog-ai
node "./src/run.js" || true
`;

    // Ensure hooks directory exists
    try {
      await fs.access(hooksDir);
    } catch {
      console.warn('[auto-changelog-ai] .git/hooks not found. Not a git repo? Skipping hook installation.');
      return;
    }

    // Write or overwrite hook
    await fs.writeFile(hookPath, hookContent, { mode: 0o755 });

    // Ensure executable permission
    await chmod(hookPath, 0o755);

    console.log('[auto-changelog-ai] Installed git post-commit hook:', hookPath);
  } catch (err) {
    console.error('[auto-changelog-ai] Failed to set up git hook:', err.message);
  }
}

// Execute if file is run directly (npm install / postinstall)
if (import.meta.url === `file://${process.cwd()}/src/setupHook.js`) {
  setupHook();
}

export default setupHook;
